# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 54c16be637af3680ec547469fd26d7789df738b1768b901ea66e855a49fdee65decff58751462612277ba86d87e6757c0e9a437e393f9e2462db412dfec9530b

test:
  secret_key_base: 9852409e820d853063d9a52209a9eaee746f3e83e0f6abfe578063df7d237d553187b4991930bcfd98aded459c6c9d2659779a83c81f23116a59dc09d2a308d5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
